"""Stub for ``dominate.tags``. Only the tags imported by vot are declared."""

from dominate.dom_tag import dom_tag


class html_tag(dom_tag): ...

class html(html_tag): ...
class head(html_tag): ...
class body(html_tag): ...
class title(html_tag): ...

class h1(html_tag): ...
class h2(html_tag): ...
class table(html_tag): ...
class thead(html_tag): ...
class tbody(html_tag): ...
class tr(html_tag): ...
class th(html_tag): ...
class td(html_tag): ...
class div(html_tag): ...
class p(html_tag): ...
class li(html_tag): ...
class ol(html_tag): ...
class ul(html_tag): ...
class span(html_tag): ...
class style(html_tag): ...
class link(html_tag): ...
class script(html_tag): ...
class video(html_tag): ...
class a(html_tag): ...
